apiVersion: v2
name: pagopa-stand-in-manager
description: Microservice that handles Stand-In activation/deactivation process
type: application
version: 0.106.0
appVersion: 0.2.4
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
